### ISSUE TITLE
Could you share the code about Fig. 3 and 6?

### ISSUE THREAD

**Issue by Mark-Dou** [nis-research/nn-frequency-shortcuts#1]
Thanks for such excellent work ! 
I'm very interested in the Fig. 3 and 6 in the paper ? Could you share the code about drawing them in the training process ?
Thanks a lot !

**Comment by ShunxinWang** [comment]
Hi, drawing Fig.3 and Fig. 6 needs you to save the checkpoints for the first few iterations and compute the recall and precision in advance. I saved the precision and recall with pandas.DataFrame, having a structure like: 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/WangS1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/WangS1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Step | Recall | Precision
-- | -- | --
9 | 0.686 | 0.421894
9 | 0 | 0
9 | 0.654 | 0.275484
9 | 0 | 0



</body>

</html>

The `Step' referes to the training iteration, in this table, it is the 9th iteration. And the four recall and precision values are for the four classes in the synthetic datasets.  You can then plot the figures using the following code:

```
import pandas as pd
data = pd.read_csv('your_results.csv')
Precision = {}

for c in range(4): # for synthetic datasets with four classes
    R = {}
    P = {}
    for j in range(49):
        step = 10*j+9
        p = data['Precision'][(num_class)*j+c] #read the precision for individual classes
        # r = data['Recall'][(num_class)*j+c]  # using it for recall rate
        step -=9
        P.update({step:p})
        # R.update({step:r})
    Precision.update({'class'+str(c):P})
 
dataframe = pd.DataFrame(Precision)
 

sns.heatmap(dataframe, cmap="YlGnBu", vmin = 0.4, vmax = 1,ax=axs[row,path_i],cbar=False)


```
