### ISSUE TITLE
Questions about the meaning of the TPR and FPR on the DFM-filtered testsets

### ISSUE THREAD

**Issue by C0notSilly** [nis-research/nn-frequency-shortcuts#2]
Thanks for the great work.
However, I have a question that is not so certain: Is a lower TPR and FPR on the DFM-filtered test sets indicate lesser frequency shortcuts are applied by the classifier?
Looking forward to your reply.

**Comment by ShunxinWang** [comment]
Hello, Thank you for the acknowledgement!
Regarding TPR and FPR, high values of them indicate the high discrimination power and the high specificity of the frequency set. Lower TPR and FPR simply mean that the frequency sets found in the DFMs do not form frequency shortcuts in the current dataset.  If you specifically mean that the classifier is less influenced by the frequency shortcuts with frequencies contained in the DFMs, then that's what a low TPR and FPR indicate.  There could be other frequency shortcuts (other combinations of frequency) that are not shown in the DFMs.
